In [2]:
import numpy as np
from gensim.models import KeyedVectors
from nltk.corpus import stopwords
import pandas as pd

### String preprocessing

In [18]:
def name_to_list(name):
    stripped = name.strip()
    word_list = name.split(" ")
    return list(map(lambda x: x.strip(), word_list))

def remove_symbols(word_list):
    pass

def remove_stop_words(word_list):
    words = stopwords.words('spanish')
    return list(filter(lambda x: x not in words, word_list))

###  Loading Word2Vec

In [4]:
model = KeyedVectors.load('trained_vectors')

### Load data

In [19]:
degrees = pd.read_csv('degrees.csv')
degrees = degrees[['id','title']]
degrees['title'] = degrees.apply(lambda x : " ".join(remove_stop_words(name_to_list(x['title']))),axis=1)

In [20]:
degrees

      id                                              title
0      6                           Administración Servicios
1     10               Administrador Universitario Empresas
2     32                  Bachillerato Ingeniería Comercial
3     52       Comunicación Multimedia Comunicación Digital
4     55                             Contabilidad Auditoría
5     56                                   Contador Auditor
6     57                           Contador Público Auditor
7     62                       Dirección Producción Eventos
8     73                                         Ecoturismo
9      1                                          Actuación
10     2                                  Actuación Teatral
11    14                                       Antropología
12    11                                          Agronomía
13     8                           Administración Pública
14    15                                        Arqueología
15    16                                       Arquitectura
16    17                                               Arte
17    20                                         Astronomía
18    21                                          Auditoría
19    18                                    Artes Plásticas
20    19                                     Artes Visuales
21    22                          Bachillerato (Plan Común)
22    25                   Bachillerato Ciencias Ingeniería
23    26         Bachillerato Ciencias Sociales Humanidades
24    27                               Bachillerato Derecho
25    28                            Bachillerato Enfermería
26    29                           Bachillerato Humanidades
27    31                            Bachillerato Ingeniería
28    34                              Bachillerato Medicina
29    35                           Bachillerato Odontología
..   ...                                                ...
312  268                      Pedagogía Educación Artística
313  272  Pedagogía Educación Diferencial Integral Neces...
314  349                       Teatro Comunicación Escénica
315  316  Pedagogía Matemática Computación / Licenciatur...
316   33  Bachillerato Kinesiología T. Ocupacional Nutri...
317  394      Traducción/Interpretación Idiomas Extranjeros
318  393      Traducción y/o Interpretariado Inglés-Español
319  392                          Traducción Inglés-Español
320  391                       Traducción Intérprete Inglés
321  390                                     Trabajo Social
322  389                                Terapia Ocupacional
323  388                               Teoría Historia Arte
324  387                                      Teoría Música
325  386                                           Teología
326  385                                  Tecnología Médica
327  384                                  Tecnologia Sonido
328  383                             Tecnología Informática
329  395                                Ingeniería Finanzas
330  396                               Ingeniería Marketing
331  397            Administración Negocios Internacionales
332  398               Administración Hotelera Gastronómica
333  399                 Ingeniería Expediciones Ecoturismo
334  400       Ingeniería Energia Sustentabilidad Ambiental
335  401        Ingeniería Prevención Riesgos Medioambiente
336  402                        Bachillerato Ciencias Salud
337  403                              Bachillerato Ciencias
338  404                                      Biotecnología
339  405                  Ciencias Deporte Actividad Física
340  406                         Ingeniería Civil Geografía
341  407                        Ingeniería civil matemática

[342 rows x 2 columns]